stages:
  data:
    cmd: python -m gpheat.cli gen-data --config config/config.yaml --root .
    deps:
      - config/config.yaml
      - src/gpheat/simulate/pybamm_model.py
      - src/gpheat/experiments/generate_data.py
    outs:
      - artifacts/datasets
  gpy_fit_charge:
    cmd: set PYTHONPATH=src && python -m gpheat.cli fit-gpy --mode charge --no-optimize 
    deps:  
      - config/config.yaml
      - src/gpheat/models/gpy_gp.py
      - src/gpheat/models/checkpoints.py
      - src/gpheat/plot/gpy_results.py
      - artifacts/datasets
    outs:
      - artifacts/models/charge_gpy.pkl
      #- reports/figures/charge_gpy_train_dt_dt.png
      #- reports/figures/charge_gpy_train_qrev.png

  gpy_fit_discharge:
    cmd: set PYTHONPATH=src && python -m gpheat.cli fit-gpy --mode discharge --no-optimize 
    deps:
      - config/config.yaml
      - src/gpheat/models/gpy_gp.py
      - src/gpheat/models/checkpoints.py
      - src/gpheat/plot/gpy_results.py
      - artifacts/datasets
    outs:
      - artifacts/models/discharge_gpy.pkl
      #- reports/figures/discharge_gpy_train_dt_dt.png
      #- reports/figures/discharge_gpy_train_qrev.png

  test_data:
    cmd: set PYTHONPATH=src && python -m gpheat.cli make-test --config config/config.yaml --root .
    deps:
      - config/config.yaml
      - src/gpheat/utils/experiments.py
      - src/gpheat/experiments/make_test_sets.py
      - src/gpheat/simulate/pybamm_model.py
      - src/gpheat/experiments/generate_data.py
    outs:
      - artifacts/test/charge_test.csv
      - artifacts/test/discharge_test.csv

  eval_charge:
    cmd: set PYTHONPATH=src && python -m gpheat.cli eval-gpy --mode charge
    deps:
      - config/config.yaml
      - artifacts/test/charge_test.csv
      - artifacts/models/charge_gpy.pkl
      - src/gpheat/evaluation/eval_gpy.py
      - src/gpheat/data/slicing.py
      - src/gpheat/plot/gpy_results.py
      - src/gpheat/utils/physics.py
      - src/gpheat/models/checkpoints.py
      - src/gpheat/models/gpy_gp.py
    outs:
      - reports/eval/charge

  eval_discharge:
    cmd: set PYTHONPATH=src && python -m gpheat.cli eval-gpy --mode discharge
    deps:
      - config/config.yaml
      - artifacts/test/discharge_test.csv
      - artifacts/models/discharge_gpy.pkl
      - src/gpheat/evaluation/eval_gpy.py
      - src/gpheat/data/slicing.py
      - src/gpheat/plot/gpy_results.py
      - src/gpheat/utils/physics.py
      - src/gpheat/models/checkpoints.py
      - src/gpheat/models/gpy_gp.py
    outs:
      - reports/eval/discharge

  sobol_hp_charge_mult:
    cmd: set PYTHONPATH=src && python -m gpheat.cli sobol-hp --mode charge --kernel mult
    deps:
      - config/config.yaml
      - src/gpheat/sensitivity/sobol_hp.py
      - src/gpheat/models/kernels.py
      - src/gpheat/models/gpy_gp.py
      - src/gpheat/models/checkpoints.py
      - src/gpheat/plot/sobol_plots.py
      - artifacts/datasets/tspm_grid_v4_0.csv
    metrics:
      - reports/sobol/hp/charge/mult/sensitivity_charge_mult_hp.csv
    plots:
      - reports/sobol/hp/charge/mult/*S1_bar.png
      - reports/sobol/hp/charge/mult/*ST_bar.png
      - reports/sobol/hp/charge/mult/*heatmap.png
    outs:
      - reports/sobol/hp/charge/mult

  sobol_hp_discharge_mult:
    cmd: set PYTHONPATH=src && python -m gpheat.cli sobol-hp --mode discharge --kernel mult
    deps:
      - config/config.yaml
      - src/gpheat/sensitivity/sobol_hp.py
      - src/gpheat/models/kernels.py
      - src/gpheat/models/gpy_gp.py
      - src/gpheat/models/checkpoints.py
      - src/gpheat/plot/sobol_plots.py      
      - artifacts/datasets/tspm_grid_v4_0.csv
    metrics:
      - reports/sobol/hp/discharge/mult/sensitivity_discharge_mult_hp.csv
    plots:
      - reports/sobol/hp/discharge/mult/*S1_bar.png
      - reports/sobol/hp/discharge/mult/*ST_bar.png
      - reports/sobol/hp/discharge/mult/*heatmap.png      
    outs:
      - reports/sobol/hp/discharge/mult

  # features Sobol uses a saved model; you can depend on a fit stage explicitly if you want the chain
  sobol_x_charge:
    cmd: set PYTHONPATH=src && python -m gpheat.cli sobol-x --mode charge --model artifacts/models/charge_mult.pkl
    deps:
      - config/config.yaml
      - src/gpheat/sensitivity/sobol_features.py
      - src/gpheat/models/checkpoints.py
      - src/gpheat/plot/sobol_plots.py
      - artifacts/models/charge_mult.pkl
      - artifacts/datasets/tspm_grid_v4_0.csv
    metrics:
      - reports/sobol/features/charge/sensitivity_charge_features.csv
    plots:
      - reports/sobol/features/charge/*S1_bar.png
      - reports/sobol/features/charge/*ST_bar.png
      - reports/sobol/features/charge/*heatmap.png
    outs:
      - reports/sobol/features/charge

  sobol_x_discharge:
    cmd: set PYTHONPATH=src && python -m gpheat.cli sobol-x --mode discharge --model artifacts/models/discharge_mult.pkl
    deps:
      - config/config.yaml
      - src/gpheat/sensitivity/sobol_features.py
      - src/gpheat/models/checkpoints.py
      - src/gpheat/plot/sobol_plots.py      
      - artifacts/models/discharge_mult.pkl
      - artifacts/datasets/tspm_grid_v4_0.csv
    metrics:
      - reports/sobol/features/discharge/sensitivity_discharge_features.csv
    plots:
      - reports/sobol/features/discharge/*S1_bar.png
      - reports/sobol/features/discharge/*ST_bar.png
      - reports/sobol/features/discharge/*heatmap.png
    outs:
      - reports/sobol/features/discharge

