stages:
  data:
    cmd: python -m gpheat.cli gen-data --config config/config.yaml --root .
    deps:
      - config/config.yaml
      - src/gpheat/simulate/pybamm_model.py
      - src/gpheat/experiments/generate_data.py
    outs:
      - artifacts/datasets
  train:
    cmd: python -m gpheat.cli run --config config/config.yaml --root .
    deps:
      - config/config.yaml
      - src/gpheat
    outs:
      - reports/metrics.json
      - reports/figures/prediction_test.png
