project_name: gpheat

paths:
  artifacts_root: artifacts
  datasets_dir: artifacts/datasets
  reports_dir: reports
  figures_dir: reports/figures
  metrics_file: reports/metrics.json

experiment:
  seed: 42
  durations_s: [0, 3600]          # time span for PyBaMM solve
  stop_voltage_charge: 4.1
  stop_voltage_discharge: 3.105

grid:
  temperatures_C: [0, 15, 30, 45]
  modes: ["Charge", "Discharge"]
  c_rates: [0.125, 0.25, 0.5, 0.75, 1.0]

dataset:
  name: "tspm_grid_v4_0.csv"      # output CSV file name in artifacts/datasets
